version: "3"

services:
  db:
    build: ./db
    ports:
      - 5432:5432
  app:
    build: ./app
    volumes:
      - ./app:/go/src/github.com/jonathonfry/login
    links: 
      - db
    ports:
      - 8080:8080