version: "3"

services:
  db:
    build: ./db
    ports:
      - 5432:5432
  api:
    build: ./api
    volumes:
      - ./api:/go/src/github.com/jonathonfry/login
    links: 
      - db
    ports:
      - 8080:8080  
  app:
    build:
      context: ./app
    volumes:
      - ./app/src:/app/src 
    ports:
      - 3000:3000